"""Realtime event layer: the SSE schema (the frontend contract) + the broker."""

from atlas.events.broker import EventBroker
from atlas.events.schema import (
    ALL_EVENT_TYPES,
    AgentStatusPayload,
    CandidateView,
    ContextSharePayload,
    CronStatePayload,
    CronTickPayload,
    DiscoveryMatchedPayload,
    Event,
    EventType,
    GateRejectedPayload,
    GroupFormedPayload,
    HitlRequestedPayload,
    HitlResolvedPayload,
    IntentView,
    LlmStatusPayload,
    MessageSentPayload,
    MetricsUpdatedPayload,
    PolicyReviewPayload,
    PromptAcceptedPayload,
    TaskStatePayload,
    ThreadCreatedPayload,
    TraceSpanPayload,
)

__all__ = [
    "EventBroker",
    "Event",
    "EventType",
    "ALL_EVENT_TYPES",
    "CandidateView",
    "IntentView",
    "AgentStatusPayload",
    "PromptAcceptedPayload",
    "GateRejectedPayload",
    "DiscoveryMatchedPayload",
    "TaskStatePayload",
    "ThreadCreatedPayload",
    "GroupFormedPayload",
    "MessageSentPayload",
    "ContextSharePayload",
    "PolicyReviewPayload",
    "HitlRequestedPayload",
    "HitlResolvedPayload",
    "MetricsUpdatedPayload",
    "CronTickPayload",
    "CronStatePayload",
    "LlmStatusPayload",
    "TraceSpanPayload",
]
